language: node_js
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
services:
  - docker

#check repo on vulnerabilities
before_install:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - docker run --rm --name=gitleaks zricethezav/gitleaks -v -r  https://github.com/JCofman/jc-website.git

install:
  - yarn

before_script:
  - if [ $BRANCH = master ]; then yarn build:prod; else yarn build;fi
  - yarn test 
  - yarn test:size 

script:
  - yarn build-deploy-and-alias-storybook # build and deploy storybook.jcofman.de
  # deploy to staging if not master and deploy to jcofman.de if master
  - if [ $BRANCH = master ]; then NOW_URL="$(now ./public --token=$NOW_TOKEN --target production --local-config=../now.json)"; else NOW_URL="$(now ./public --token=$NOW_TOKEN --target staging --local-config=../now.json)";fi
  # store deployment url from clipboard into the deployment url
  - echo $NOW_URL

after_success:
  # check lighthouse score
  - yarn lighthouse-ci $NOW_URL --score=90 --performance=85 --pwa=90 --accessibility=90 --best-practice=90 --seo=90
  # run webpagetest 
  - TEST_URL=$NOW_URL GIT_TOKEN=$GIT_TOKEN WEBPAGETEST_API_KEY=$WEBPAGETEST_API_KEY GIT_BRANCH=$BRANCH SLACK_HOOK_URL=$SLACK_HOOK_URL node webPageTest.js

env:
  global:
    - secure: fz3Aud9IxEtyZ6RYoMUXuXtF4VZMhiQRSXgivK1yxLpjSM/jjNWsbf8enOpegs33nxWu2tRH87WvqtG2Wn2vvrupzCA/9i4uurMgve6bunwGaIlKPgChb+bSJPwzhn7m15dyG34GYMOL8358QjwU/GFPV2yrEB88phRp6OCCHuFkFsGdTWn2NaHrl0v1VvGkRS8U/TzOjHhMwfWwIoSaStA8rDQrmxWwqxllnBIDWulVbSCP5Oy7/VbPAgZHt1BqNRvwAVxyGVLXtuTOOyFDlv4excRHFlxkmFKDcmod/4M+INPyIxiPsJzK/yLNd2iddyHzKhtLKmAM7ILrbVZwOgodHKyF0dRLOo0I3+fjLrVy9IOTHUabTEOESna8ErPeoqYbACWl5+MPjKSEbm2MOQFjKn4KnfN4tbzzu/Sp5yNwf6fXtPjbfHa9M/pDURGMFlECuV9rePilnEsyRccg1vR+SzRv4pT8wpGL8L2d3+o3boqTtC6w3fpS23nleLwE1tVn9NZYxE38MB3njI/k61VHkOo9R2SyiqHQTC/Z8hjmNuEbwiEypK+KJcjap4ytcpz1tQxXAFppyjtWxFOAY630pY6EkmKRAI8lgtArBwIqB5hIBBKUff6cMC/7lgtzysvv41hDGpdgU0U8gguGygFmUUwaQu156M+kVbTrwr4=
